### ISSUE TITLE
ERROR 500 - internal server error

### ISSUE THREAD

**Issue by fengler-it** [yzzy/responsive_redmine_tables#2]
Using this plugin results in 

`tail -50 ../log/production.log 
  Rendered issues/_form_custom_fields.html.erb (0.2ms)
  Rendered issues/_attributes.html.erb (50.2ms)
  Rendered issues/_form.html.erb (83.4ms)
  Rendered attachments/_form.html.erb (4.5ms)
  Rendered issues/_edit.html.erb (101.7ms)
  Rendered issues/edit.html.erb within layouts/base (107.0ms)
Completed 200 OK in 272ms (Views: 126.7ms | ActiveRecord: 78.5ms)
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Started GET "/tasks/my/account" for 77.3.33.194 at 2019-06-10 09:33:35 +0200
Processing by MyController#account as HTML
  Current user: tf (id=6)
  Rendering my/account.html.erb within layouts/base
  Rendered users/_mail_notifications.html.erb (97.7ms)
  Rendered users/_preferences.html.erb (396.7ms)
  Rendered my/_sidebar.html.erb (84.9ms)
  Rendered my/account.html.erb within layouts/base (759.7ms)
Missing template, responding with 404: Missing partial layouts/_base_html_head with {:locale=>[:de, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
  * "/opt/redmine/redmine-4.0.2/app/views"

  Rendering common/error.html.erb within layouts/base
  Rendered common/error.html.erb within layouts/base (1.4ms)
Completed 500 Internal Server Error in 1079ms (ActiveRecord: 81.2ms)
  
ActionView::Template::Error (Missing partial layouts/_base_html_head with {:locale=>[:de, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
  * "/opt/redmine/redmine-4.0.2/app/views"
):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: 
    18: <%= yield :header_tags -%>
    19: </head>
  
lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
lib/redmine/hook/view_listener.rb:57:in `map'
lib/redmine/hook/view_listener.rb:57:in `block in render_on'
lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:61:in `each'
lib/redmine/hook.rb:61:in `block in call_hook'
lib/redmine/hook.rb:58:in `tap'
lib/redmine/hook.rb:58:in `call_hook'
lib/redmine/hook.rb:96:in `call_hook'
app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb__2620652835887422267_46982686942780'
app/controllers/application_controller.rb:499:in `block (2 levels) in render_error'
app/controllers/application_controller.rb:497:in `render_error'
app/controllers/application_controller.rb:485:in `render_404'
app/controllers/application_controller.rb:509:in `missing_template'
`

**Comment by yzzy** [comment]
@fengler-it 
Sorry, I can't reproduce it with fresh 4.0.2 Redmine with only this plugin installed.
Did you restart Redmine and front-end web server (if any) after plugin installation?
Which additional plugins do you have? Seems that route `/tasks/my/account` doesn't exist on default Redmine.

**Comment by fengler-it** [comment]
Hi and thanks for your fast reply.

Yes, I did restart apache2. As far as i know (newbie), Redmine is running as a container in apache2, so - when I restart apacha2, Redmine ist being restarted. Right?

I don't have any other plugins installed, just some themes.

And here you can see .../tasks/my/account [https://abload.de/img/my.accountlmj7d.jpg]

**Comment by fengler-it** [comment]
Additional info: `Environment:
  Redmine version               4.0.2.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Filesystem                     
Tasks plugins:
  no plugin installed`

**Comment by fengler-it** [comment]
Running on a "Debian 4.19.37-3~bpo9+1" system

**Comment by yzzy** [comment]
> Redmine is running as a container in apache2, so - when I restart apacha2, Redmine ist being restarted

Generally speaking, no. If Apache is on one container (Docker?) and Redmine is on another, these containers are completely independent without some kind of orchestration. If Redmine installed within Apache container then restarting Apache service doesn't mean restarting Redmine service, there is no dependency too unless you have Passenger AFAIK.
So please manually restart Redmine at first, Apache at second, and let me know if it helps.

**Comment by fengler-it** [comment]
Well, I am using Passenger (AFAIK) and I don't know, how to restart redmine by other means than restarting apache.

`service apache2 status
\u25cf apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-06-10 22:03:17 CEST; 57s ago
  Process: 2290 ExecStop=/usr/sbin/apachectl stop (code=exited, status=0/SUCCESS)
  Process: 16165 ExecReload=/usr/sbin/apachectl graceful (code=exited, status=0/SUCCESS)
  Process: 2306 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
 Main PID: 1644 (code=exited, status=0/SUCCESS)
    Tasks: 100 (limit: 4915)
   CGroup: /system.slice/apache2.service
           \u251c\u25002348 /usr/sbin/apache2 -k start
           \u251c\u25002349 Passenger watchdog
           \u251c\u25002356 Passenger core
           \u251c\u25002362 Passenger ust-router
           \u251c\u25002384 /usr/sbin/apache2 -k start
           \u251c\u25002389 /usr/sbin/apache2 -k start
           \u251c\u25002394 /usr/sbin/apache2 -k start
           \u251c\u25002399 /usr/sbin/apache2 -k start
           \u251c\u25002404 /usr/sbin/apache2 -k start
           \u251c\u25002435 Passenger AppPreloader: /opt/redmine/redmine-4.0.2
           \u251c\u25002441 /usr/sbin/apache2 -k start
           \u251c\u25002456 Passenger RubyApp: /opt/redmine/redmine-4.0.2 (production)
           \u251c\u25002472 /usr/sbin/apache2 -k start
           \u251c\u25002479 /usr/sbin/apache2 -k start
           \u251c\u25002484 /usr/sbin/apache2 -k start
           \u251c\u25002489 /usr/sbin/apache2 -k start
           \u251c\u25002494 /usr/sbin/apache2 -k start
           \u251c\u25002495 /usr/sbin/apache2 -k start
           \u2514\u25002500 /usr/sbin/apache2 -k start

Jun 10 22:03:16 nas1 systemd[1]: Starting The Apache HTTP Server...
Jun 10 22:03:17 nas1 systemd[1]: Started The Apache HTTP Server.`

**Comment by yzzy** [comment]
Sorry, didn't notice immediately:
> Additional info: Environment: Redmine version 4.0.2.stable Ruby version 2.3.3-p222 (2016-11-21) [x86_64-linux-gnu] Rails version 5.2.2 Environment production Database adapter Mysql2 Mailer queue ActiveJob::QueueAdapters::AsyncAdapter Mailer delivery smtp SCM: Filesystem Tasks plugins: **no plugin installed**

It seems the plugin has not been properly installed.
Please make sure the plugin is cloned exactly into
`/opt/redmine/redmine-4.0.2/plugins/responsive_redmine_tables`

By the way I've tested my plugin with **PurpleMine2 v.2.5.0** theme, it works fine.

**Comment by fengler-it** [comment]
Redmine is producing the ERROR 500 immediately after installing the plugin.
The info (showing that no plugin is installed) was produced after de-installing the plugin.

Perhaps my problem has something to do with paths?

**Comment by fengler-it** [comment]
YES! It was the path. When downloading the plugin's zipfile, it contains a directory named "responsive_redmine_tables-master". I didn't notice before and unzipped it directly into the .../plugins directory (resulting in ERROR 500).

After a "mv responsive_redmine_tables-master/ responsive_redmine_tables" and a restart of apache2 everything works fine. :-)

Thanks for your help and patience.

Спасибо

**Comment by yzzy** [comment]
So far, so good
If you like this plugin please rate it at [Redmine Plugins Directory](http://www.redmine.org/plugins)
My email is specified in the profile, feel free to ask about Redmine
